export const types = {
    OPEN_CHATLIST_REQUEST: 'OPEN_CHATLIST_REQUEST',
    OPEN_CHATLIST_SUCCESS: 'OPEN_CHATLIST_SUCCESS',
    OPEN_CHATLIST_FAILURE: 'OPEN_CHATLIST_FAILURE',

    SET_MESSAGES_REQUEST: 'SET_MESSAGES_REQUEST',
    SET_MESSAGES_SUCCESS: 'SET_MESSAGES_SUCCESS',
    SET_MESSAGES_FAILURE: 'SET_MESSAGES_FAILURE',

    GET_NOTIFICATION_REQUEST: 'GET_NOTIFICATION_REQUEST',
    GET_NOTIFICATION_SUCCESS: 'GET_NOTIFICATION_SUCCESS',
    GET_NOTIFICATION_FAILURE: 'GET_NOTIFICATION_FAILURE',

    SELECT_CHAT_REQUEST: 'SELECT_CHAT_REQUEST',
    SELECT_CHAT_SUCCESS: 'SELECT_CHAT_SUCCESS',
    SELECT_CHAT_FAILURE: 'SELECT_CHAT_FAILURE',

    FETCH_MESSAGES_REQUEST: 'FETCH_MESSAGES_REQUEST',
    FETCH_MESSAGES_SUCCESS: 'FETCH_MESSAGES_SUCCESS',
    FETCH_MESSAGES_FAILURE: 'FETCH_MESSAGES_FAILURE',
  }